name: Terraform Security Check

on:
  push:
    branches:
      - secure
  pull_request:
    types: [closed]
    branches:
      - main


jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
    - name: Run tfsec
      run: tfsec --minimum-severity HIGH --detailed-exit-code terraform/dev

