name: Terraform Security Check

on:
  push:
    branches:
      - secure

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
    - name: Run tfsec
      run: tfsec terraform/dev

